spring.application.name=hoseo-chatbot

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
server.port=8080

rag.server.url=https://wriggle-script-caption.ngrok-free.dev

spring.profiles.include=local

# 민감한 값은 application-local.properties 에 작성 (git 제외)