spring.datasource.url=jdbc:mysql://localhost:3307/hoseo_chatbot?sslMode=DISABLED&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

notice.api-key=hoseo-lens-secret-key
admin.api-key=hoseo-admin-secret-key

server.error.include-stacktrace=never
server.error.include-message=always
